const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'../..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const block=html.match(/const firebaseConfig = (\{[\s\S]*?\});/);
if(!block)throw new Error('Existing Firebase configuration missing');
const vm=require('vm');const config=JSON.parse(fs.readFileSync(path.join(root,'native-android/firebase-android-client.json'),'utf8'));
if(!/^1:\d+:android:/.test(config.appId))throw new Error('Registered native Android Firebase app required');
if(!/^\d+$/.test(config.messagingSenderId))throw new Error('FCM sender id missing');
for(const key of ['apiKey','appId','projectId','databaseURL'])if(typeof config[key]!=='string'||!config[key])throw new Error('Incomplete client config');
if(!config.databaseURL.startsWith('https://'))throw new Error('HTTPS required');
const dir=path.resolve(__dirname,'../app/src/main/assets');fs.mkdirSync(dir,{recursive:true});
fs.writeFileSync(path.join(dir,'firebase-client.json'),JSON.stringify(config));
const readConstant=(name)=>{const expr=html.match(new RegExp('const '+name+'\\s*=\\s*([\\s\\S]*?);'));if(!expr)throw new Error('Missing public vision setting: '+name);return vm.runInNewContext('('+expr[1]+')');};
fs.writeFileSync(path.join(dir,'vision-client.json'),JSON.stringify({geminiModels:readConstant('GEMINI_MODELS'),grokModels:readConstant('GROK_MODELS'),prompt:readConstant('AI_PHOTO_PROMPT')}));
console.log('Public Firebase client configuration prepared; no server credentials');
